export type DataFormat = 'markdown' | 'json' | 'csv' | 'unknown';

export interface ColumnMapping {
  source: string;
  target: string;
  targetTable?: string;
  confidence: number; // 0-1 for auto-mapping
  transform?: (value: any) => any;
  sourceType?: string;
  targetType?: string;
  isIgnored?: boolean; // Useful for skipping columns
}

export interface ValidationError {
  type: 'duplicate' | 'type_mismatch' | 'schema_mismatch' | 'format_error';
  message: string;
  rowIndex?: number;
  column?: string;
  suggestedFix?: string;
}

export interface ParseError {
  type: 'malformed_row' | 'column_mismatch' | 'empty_table' | 'invalid_separator' | 'format_error' | 'malformed_table';
  message: string;
  line?: number;
  column?: number;
  rawContent?: string;
  suggestion?: string;
}

export interface AlternativeParsing {
  multiColumn?: {
    headers: string[];
    rows: any[];
    columnCount: number;
    rowCount: number;
  };
}

export interface ParseResult {
  headers: string[];
  rows: any[];
  errors: ParseError[];
  metadata: {
    rowCount: number;
    columnCount: number;
    hasSeparatorRow: boolean;
    formatDetected: 'pipe' | 'grid' | 'minimal' | 'headings' | 'json' | 'csv' | 'unknown';
    sampleValues: { [column: string]: any[] };
    alternativeParsing?: AlternativeParsing;
  };
}

export interface DatabaseConnection {
  id: string;
  name: string;
  host: string;
  port: number;
  database: string;
  username: string;
  password?: string;
  isDefault: boolean;
  lastUsed: Date;
}

export interface SmartLink {
  targetTable: string;      // The child table (e.g., 'posts')
  targetColumn: string;     // The FK column (e.g., 'user_id')
  foreignTable: string;     // The parent table (e.g., 'users')
  foreignKey: string;       // The ID column in parent (e.g., 'id')
  foreignLabel: string;     // The human readable column (e.g., 'email')
}

export interface ColumnInfo {
  name: string;
  dataType: string;
  isNullable: boolean;
  columnDefault: string | null;
  isAutoGenerated: boolean; // True for SERIAL, auto_increment, etc.
  isGenerated: boolean;     // True for GENERATED ALWAYS AS ... STORED
  isIdentity: boolean;      // True for GENERATED ALWAYS AS IDENTITY
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  foreignKeyTable?: string;
  foreignKeyColumn?: string;
}

export interface MissingColumnValue {
  tableName: string;
  columnName: string;
  columnInfo: ColumnInfo;
  value: string | null; // User-provided value or selected FK value
  isForeignKey: boolean;
}
