import { useState, useEffect } from 'react';
import { ArrowRight, Check, X, Wand2, Database, RefreshCw, AlertTriangle } from 'lucide-react';
import { cn } from '../../lib/utils';
import { ParseResult, ColumnMapping, SmartLink, ColumnInfo } from '../../types';

interface ColumnMapperProps {
    parseResult: ParseResult;
    onMappingComplete: (mappings: ColumnMapping[]) => void;
    className?: string;
    tables: string[];
    onRefreshTables?: () => void;
    onFetchColumns: (tableName: string) => Promise<ColumnInfo[]>;
    smartLinks: SmartLink[];
    onSmartLinkChange: (links: SmartLink[]) => void;
    isConnected: boolean;
    onOpenConnection: () => void;
}

export function ColumnMapper({
    parseResult,
    onMappingComplete,
    className,
    tables,
    onRefreshTables,
    onFetchColumns,
    smartLinks,
    onSmartLinkChange,
    isConnected,
    onOpenConnection
}: ColumnMapperProps) {
    const [mappings, setMappings] = useState<ColumnMapping[]>([]);

    // Track which column is currently being linked { sourceIndex, foreignTable }
    const [activeLinkConfig, setActiveLinkConfig] = useState<{ index: number, foreignTable: string } | null>(null);

    // Track fetched columns for each table
    const [tableColumnsMap, setTableColumnsMap] = useState<Record<string, ColumnInfo[]>>({});

    // Track which column is selecting a display field for SmartLink
    const [selectingDisplayFor, setSelectingDisplayFor] = useState<number | null>(null);

    // Initialize mappings when parseResult changes
    useEffect(() => {
        if (!parseResult) return;

        const initialMappings: ColumnMapping[] = parseResult.headers.map(header => {
            return {
                source: header,
                target: toSnakeCase(header),
                targetTable: '',
                confidence: 0.5,
                sourceType: inferType(parseResult.metadata.sampleValues[header]),
                isIgnored: false
            };
        });

        setMappings(initialMappings);
    }, [parseResult]);

    useEffect(() => {
        onMappingComplete(mappings);
    }, [mappings, onMappingComplete]);

    const handleTableChange = async (index: number, table: string) => {
        const newMappings = [...mappings];
        newMappings[index].targetTable = table;
        setMappings(newMappings);

        // Fetch columns for the selected table
        if (table && !tableColumnsMap[table]) {
            const columns = await onFetchColumns(table);
            setTableColumnsMap(prev => ({
                ...prev,
                [table]: columns
            }));

            // Auto-detect SmartLinks for foreign keys
            const fkColumns = columns.filter(col => col.isForeignKey);
            if (fkColumns.length > 0) {
                const newLinks: SmartLink[] = [...smartLinks];

                for (const fkCol of fkColumns) {
                    // Check if SmartLink already exists
                    const exists = newLinks.some(
                        link => link.targetTable === table && link.targetColumn === fkCol.name
                    );

                    if (!exists && fkCol.foreignKeyTable && fkCol.foreignKeyColumn) {
                        // Fetch columns from foreign table to suggest a display column
                        const foreignColumns = await onFetchColumns(fkCol.foreignKeyTable);

                        // Try to find a good display column (prefer name, title, email, etc.)
                        const displayCol = foreignColumns.find(col =>
                            !col.isAutoGenerated &&
                            !col.isPrimaryKey &&
                            (col.name.includes('name') || col.name.includes('title') || col.name.includes('email'))
                        ) || foreignColumns.find(col => !col.isAutoGenerated && !col.isPrimaryKey);

                        newLinks.push({
                            targetTable: table,
                            targetColumn: fkCol.name,
                            foreignTable: fkCol.foreignKeyTable,
                            foreignKey: fkCol.foreignKeyColumn,
                            foreignLabel: displayCol?.name || fkCol.foreignKeyColumn
                        });
                    }
                }

                onSmartLinkChange(newLinks);
            }
        }
    };

    const handleTargetChange = (index: number, value: string) => {
        const newMappings = [...mappings];
        newMappings[index].target = value;
        setMappings(newMappings);
    };

    const handleTypeChange = (index: number, value: string) => {
        const newMappings = [...mappings];
        newMappings[index].sourceType = value;
        setMappings(newMappings);
    };

    const toggleIgnore = (index: number) => {
        const newMappings = [...mappings];
        newMappings[index].isIgnored = !newMappings[index].isIgnored;
        setMappings(newMappings);
    };

    const getSmartLinkData = (targetColumn: string) => {
        return smartLinks.find(l => l.targetColumn === targetColumn);
    };

    return (
        <div className={cn("space-y-6", className)}>
            <div className="flex items-center justify-between">
                <h3 className="text-xl font-bold text-white tracking-wide flex items-center gap-3">
                    <Wand2 className="w-5 h-5 text-ember" />
                    Column Mapping
                </h3>
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2 text-xs text-khaki-beige bg-gunmetal/50 px-3 py-1 rounded-full border border-taupe">
                        <Database className="w-3 h-3" />
                        {tables.length} Tables Available
                        {onRefreshTables && (
                            <button
                                onClick={(e) => {
                                    e.preventDefault();
                                    onRefreshTables();
                                }}
                                className="ml-1 hover:text-white transition-colors"
                                title="Refresh Table List"
                            >
                                <RefreshCw className="w-3 h-3" />
                            </button>
                        )}
                    </div>
                    <p className="text-sm text-gray-400">
                        Map {parseResult.headers.length} source columns
                    </p>
                </div>
            </div>

            {!isConnected && (
                <div className="bg-amber-900/20 border border-amber-500/30 rounded-xl p-6 flex flex-col items-center text-center space-y-4 animate-in fade-in slide-in-from-top-4">
                    <div className="w-12 h-12 bg-amber-500/20 rounded-full flex items-center justify-center">
                        <Database className="w-6 h-6 text-amber-500" />
                    </div>
                    <div>
                        <h4 className="text-white font-bold">Database Not Connected</h4>
                        <p className="text-sm text-gray-400 mt-1">Connect to a database to load tables and validate columns.</p>
                    </div>
                    <button
                        onClick={onOpenConnection}
                        className="px-6 py-2 bg-amber-600 hover:bg-amber-500 text-white rounded-lg text-sm font-bold transition-colors"
                    >
                        Connect Database
                    </button>
                </div>
            )}

            {isConnected && tables.length === 0 && (
                <div className="bg-blue-900/20 border border-blue-500/30 rounded-xl p-6 flex flex-col items-center text-center space-y-4 animate-in fade-in slide-in-from-top-4">
                    <div className="w-12 h-12 bg-blue-500/20 rounded-full flex items-center justify-center">
                        <AlertTriangle className="w-6 h-6 text-blue-400" />
                    </div>
                    <div>
                        <h4 className="text-white font-bold">No Tables Found</h4>
                        <p className="text-sm text-gray-400 mt-1">We couldn't find any tables in the public schema of the connected database.</p>
                    </div>
                    {onRefreshTables && (
                        <button
                            onClick={onRefreshTables}
                            className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-bold transition-colors flex items-center gap-2"
                        >
                            <RefreshCw className="w-4 h-4" />
                            Refresh Tables
                        </button>
                    )}
                </div>
            )}

            {/* Legend/Info Section */}
            {isConnected && tables.length > 0 && (
                <div className="bg-taupe/10 border border-taupe/50 rounded-lg p-3 mb-4">
                    <div className="flex items-center gap-6 text-xs text-gray-400 flex-wrap">
                        <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded bg-red-500/10 text-red-400 border border-red-500/20 font-bold">*</span>
                            <span>Required field (NOT NULL)</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded bg-green-500/10 text-green-400 border border-green-500/20 font-bold">AUTO</span>
                            <span>Auto-generated (excluded from insertion)</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded bg-purple-900/80 text-purple-200 border border-purple-500/50 font-bold">FK</span>
                            <span>Foreign Key (SmartLink active)</span>
                        </div>
                    </div>
                </div>
            )}

            <div className="bg-gunmetal/50 border border-taupe rounded-xl overflow-hidden shadow-2xl pb-32">
                <div className="overflow-x-auto overflow-y-visible">
                    <table className="w-full text-left">
                        <thead>
                            <tr className="bg-taupe/30 border-b border-taupe text-xs uppercase tracking-wider text-khaki-beige font-bold">
                                <th className="px-6 py-4">Source Column</th>
                                <th className="px-6 py-4 text-center">Map</th>
                                <th className="px-6 py-4">Target Table : Column</th>
                                <th className="px-6 py-4 relative">
                                    Type
                                </th>
                                <th className="px-6 py-4 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-taupe/20">
                            {mappings.map((map, idx) => {
                                const activeLink = getSmartLinkData(map.target);

                                return (
                                    <tr
                                        key={idx}
                                        className={cn(
                                            "group transition-colors relative",
                                            map.isIgnored ? "bg-gunmetal/80 opacity-50" : "hover:bg-taupe/10"
                                        )}
                                    >
                                        <td className="px-6 py-4">
                                            <div className="font-medium text-gray-200">{map.source}</div>
                                            <div className="text-xs text-gray-500 mt-1 truncate max-w-[150px]">
                                                Ex: {parseResult.metadata.sampleValues[map.source]?.[0] || '-'}
                                            </div>
                                        </td>

                                        <td className="px-6 py-4 text-center">
                                            <ArrowRight className={cn(
                                                "w-4 h-4 mx-auto transition-transform",
                                                map.isIgnored ? "text-gray-600" : "text-ember group-hover:translate-x-1"
                                            )} />
                                        </td>

                                        <td className="px-6 py-4 relative z-10">
                                            <div className="flex items-center gap-2">
                                                <div className="relative flex-1">
                                                    <select
                                                        value={map.targetTable || ''}
                                                        onChange={(e) => handleTableChange(idx, e.target.value)}
                                                        disabled={map.isIgnored}
                                                        className={cn(
                                                            "w-full bg-gunmetal border border-taupe rounded-lg px-2 py-2 text-sm font-mono appearance-none transition-all outline-none",
                                                            map.isIgnored ? "text-gray-600 cursor-not-allowed" : "text-white focus:border-ember"
                                                        )}
                                                    >
                                                        <option value="">Select Table...</option>
                                                        {tables.map(t => (
                                                            <option key={t} value={t}>{t}</option>
                                                        ))}
                                                    </select>
                                                </div>

                                                <span className="text-gray-600 font-bold">:</span>

                                                <div className="relative flex-1">
                                                    <select
                                                        value={map.target}
                                                        onChange={(e) => handleTargetChange(idx, e.target.value)}
                                                        disabled={map.isIgnored || !map.targetTable}
                                                        className={cn(
                                                            "w-full bg-gunmetal border rounded-lg px-3 py-2 text-sm font-mono appearance-none transition-all focus:ring-2 outline-none",
                                                            "border-taupe text-white focus:border-ember focus:ring-ember/50",
                                                            (map.isIgnored || !map.targetTable) && "border-transparent text-gray-600 cursor-not-allowed bg-taupe/10"
                                                        )}
                                                    >
                                                        <option value="">Select Column...</option>
                                                        {map.targetTable && tableColumnsMap[map.targetTable] &&
                                                            tableColumnsMap[map.targetTable]
                                                                .filter(col => (!col.isAutoGenerated && !col.isGenerated && !col.isIdentity) || col.isForeignKey)
                                                                .map(col => (
                                                                    <option key={col.name} value={col.name}>
                                                                        {col.name}
                                                                        {!col.isNullable && !col.isAutoGenerated && !col.isGenerated && !col.isIdentity && !col.columnDefault ? ' *' : ''}
                                                                        {col.isForeignKey ? ' (FK)' : ''}
                                                                    </option>
                                                                ))
                                                        }
                                                    </select>
                                                </div>
                                            </div>

                                            {activeLink && (
                                                <div className="absolute -bottom-2 right-0 flex items-center gap-1">
                                                    <div className="text-[10px] bg-purple-900/80 text-purple-200 px-2 rounded-b-md border-x border-b border-purple-500/50">
                                                        Link: {activeLink.foreignTable}.{activeLink.foreignLabel}
                                                    </div>
                                                    <button
                                                        onClick={() => setSelectingDisplayFor(selectingDisplayFor === idx ? null : idx)}
                                                        className="text-[10px] bg-purple-700 hover:bg-purple-600 text-white px-2 py-0.5 rounded-b-md transition-colors"
                                                        title="Change display column"
                                                    >
                                                        ⚙
                                                    </button>
                                                </div>
                                            )}

                                            {/* Display Column Selector */}
                                            {selectingDisplayFor === idx && activeLink && (
                                                <div className="absolute top-full left-0 mt-2 w-64 bg-gunmetal border border-purple-500 shadow-2xl rounded-xl p-3 z-50 animate-in fade-in zoom-in-95">
                                                    <div className="flex items-center justify-between mb-2 pb-2 border-b border-taupe/50">
                                                        <span className="text-xs font-bold text-white">Select Display Column</span>
                                                        <button onClick={() => setSelectingDisplayFor(null)} className="text-gray-500 hover:text-white">
                                                            <X className="w-3 h-3" />
                                                        </button>
                                                    </div>

                                                    {tableColumnsMap[activeLink.foreignTable] ? (
                                                        <div className="space-y-1">
                                                            {tableColumnsMap[activeLink.foreignTable]
                                                                .filter(col => !col.isAutoGenerated || col.isPrimaryKey)
                                                                .map(col => (
                                                                    <button
                                                                        key={col.name}
                                                                        onClick={() => {
                                                                            const newLinks = smartLinks.map(link =>
                                                                                link.targetTable === activeLink.targetTable &&
                                                                                    link.targetColumn === activeLink.targetColumn
                                                                                    ? { ...link, foreignLabel: col.name }
                                                                                    : link
                                                                            );
                                                                            onSmartLinkChange(newLinks);
                                                                            setSelectingDisplayFor(null);
                                                                        }}
                                                                        className={cn(
                                                                            "w-full text-left px-2 py-1 rounded text-xs transition-colors",
                                                                            col.name === activeLink.foreignLabel
                                                                                ? "bg-purple-600 text-white"
                                                                                : "hover:bg-taupe/20 text-gray-300"
                                                                        )}
                                                                    >
                                                                        {col.name}
                                                                        {col.isPrimaryKey && <span className="ml-1 text-[8px] text-purple-300">(PK)</span>}
                                                                    </button>
                                                                ))}
                                                        </div>
                                                    ) : (
                                                        <div className="text-xs text-gray-400 italic">Loading columns...</div>
                                                    )}
                                                </div>
                                            )}
                                        </td>

                                        <td className="px-6 py-4 relative">
                                            <div className="flex flex-col gap-2 items-start">
                                                <div className="flex items-center gap-2 flex-wrap">
                                                    <select
                                                        value={map.sourceType || 'string'}
                                                        onChange={(e) => handleTypeChange(idx, e.target.value)}
                                                        disabled={map.isIgnored}
                                                        className={cn(
                                                            "px-2 py-1 rounded text-xs font-bold border w-fit appearance-none outline-none cursor-pointer hover:bg-opacity-80 transition-all",
                                                            map.sourceType === 'number' && "bg-blue-500/10 text-blue-400 border-blue-500/20",
                                                            map.sourceType === 'boolean' && "bg-purple-500/10 text-purple-400 border-purple-500/20",
                                                            map.sourceType === 'date' && "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
                                                            (map.sourceType === 'string' || !map.sourceType) && "bg-gray-500/10 text-gray-400 border-gray-500/20",
                                                        )}
                                                    >
                                                        <option value="string" className="bg-gunmetal text-gray-300">String</option>
                                                        <option value="number" className="bg-gunmetal text-blue-400">Number</option>
                                                        <option value="boolean" className="bg-gunmetal text-purple-400">Boolean</option>
                                                        <option value="date" className="bg-gunmetal text-emerald-400">Date</option>
                                                    </select>
                                                    {map.targetTable && tableColumnsMap[map.targetTable] && (() => {
                                                        const targetCol = tableColumnsMap[map.targetTable].find(c => c.name === map.target);
                                                        if (!targetCol) return null;
                                                        return (
                                                            <>
                                                                {!targetCol.isNullable && !targetCol.isAutoGenerated && !targetCol.isGenerated && !targetCol.isIdentity && !targetCol.columnDefault && (
                                                                    <span className="px-2 py-1 rounded text-xs font-bold border bg-red-500/10 text-red-400 border-red-500/20">
                                                                        REQUIRED
                                                                    </span>
                                                                )}
                                                                {(targetCol.isAutoGenerated || targetCol.isGenerated || targetCol.isIdentity) && (
                                                                    <span className="px-2 py-1 rounded text-xs font-bold border bg-green-500/10 text-green-400 border-green-500/20">
                                                                        AUTO
                                                                    </span>
                                                                )}
                                                            </>
                                                        );
                                                    })()}
                                                </div>
                                            </div>

                                            {activeLinkConfig?.index === idx && (
                                                <div className="absolute top-full left-0 mt-2 w-64 bg-gunmetal border border-taupe shadow-2xl rounded-xl p-3 z-50 animate-in fade-in zoom-in-95 backdrop-blur-md ring-1 ring-white/10">
                                                    <div className="flex items-center justify-between mb-2 pb-2 border-b border-taupe/50">
                                                        <span className="text-xs font-bold text-white flex items-center gap-2">
                                                            Database Info
                                                        </span>
                                                        <button onClick={() => setActiveLinkConfig(null)} className="text-gray-500 hover:text-white">
                                                            <X className="w-3 h-3" />
                                                        </button>
                                                    </div>

                                                    <div className="py-2 text-[10px] text-gray-400 italic">
                                                        Note: Automatic schema lookup is currently disabled to improve performance. Please enter column names manually.
                                                    </div>
                                                </div>
                                            )}
                                        </td>

                                        <td className="px-6 py-4 text-right">
                                            <button
                                                onClick={() => toggleIgnore(idx)}
                                                className={cn(
                                                    "p-2 rounded-lg transition-colors",
                                                    map.isIgnored
                                                        ? "bg-taupe text-gray-400 hover:text-white"
                                                        : "text-gray-500 hover:text-red-400 hover:bg-red-900/20"
                                                )}
                                                title={map.isIgnored ? "Enable column" : "Ignore column"}
                                            >
                                                {map.isIgnored ? <Check className="w-4 h-4" /> : <X className="w-4 h-4" />}
                                            </button>
                                        </td>
                                    </tr>
                                )
                            })}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}

// Helper to infer type from a sample array
function inferType(samples: any[]): string {
    if (!samples || samples.length === 0) return 'string';

    const sample = samples.find(s => s !== null && s !== undefined && s !== '');
    if (sample === undefined) return 'string';

    if (typeof sample === 'boolean' || sample === 'true' || sample === 'false') return 'boolean';
    if (typeof sample === 'number' || !isNaN(Number(sample))) return 'number';

    const date = new Date(sample);
    if (!isNaN(date.getTime()) && sample.length > 5) return 'date';

    return 'string';
}

function toSnakeCase(str: string): string {
    return str
        .replace(/([a-z])([A-Z])/g, '$1_$2')
        .replace(/[\s-]+/g, '_')
        .toLowerCase();
}
